spring:
  jooq:
    sql-dialect: h2

  application:
    name: nexign-demo

  liquibase:
    change-log: classpath:/db/changelog/master.xml

  h2:
    console:
      enabled: true
  
  datasource:
    url: jdbc:h2:mem:CDR_DB
    username: sa
    password: password
    driver-class-name: org.h2.Driver

generator:
    subscribers:
      amount: 100
    cdrs: 
      amount: 10000