/*
 * This file is generated by jOOQ.
 */
package ru.crackedglass.nexign_demo.entities.jooq.tables.records;


import java.time.Instant;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.crackedglass.nexign_demo.entities.jooq.tables.Cdrs;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CdrsRecord extends UpdatableRecordImpl<CdrsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CDRS.CDR_ID</code>.
     */
    public void setCdrId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CDRS.CDR_ID</code>.
     */
    public Long getCdrId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CDRS.CALL_TYPE</code>.
     */
    public void setCallType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CDRS.CALL_TYPE</code>.
     */
    public String getCallType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CDRS.CALLER_SUBSCRIBER_ID</code>.
     */
    public void setCallerSubscriberId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>CDRS.CALLER_SUBSCRIBER_ID</code>.
     */
    public Long getCallerSubscriberId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>CDRS.RECEIVER_SUBSCRIBER_ID</code>.
     */
    public void setReceiverSubscriberId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>CDRS.RECEIVER_SUBSCRIBER_ID</code>.
     */
    public Long getReceiverSubscriberId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>CDRS.START_TIMESTAMP</code>.
     */
    public void setStartTimestamp(Instant value) {
        set(4, value);
    }

    /**
     * Getter for <code>CDRS.START_TIMESTAMP</code>.
     */
    public Instant getStartTimestamp() {
        return (Instant) get(4);
    }

    /**
     * Setter for <code>CDRS.END_TIMESTAMP</code>.
     */
    public void setEndTimestamp(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>CDRS.END_TIMESTAMP</code>.
     */
    public Instant getEndTimestamp() {
        return (Instant) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CdrsRecord
     */
    public CdrsRecord() {
        super(Cdrs.CDRS);
    }

    /**
     * Create a detached, initialised CdrsRecord
     */
    public CdrsRecord(Long cdrId, String callType, Long callerSubscriberId, Long receiverSubscriberId, Instant startTimestamp, Instant endTimestamp) {
        super(Cdrs.CDRS);

        setCdrId(cdrId);
        setCallType(callType);
        setCallerSubscriberId(callerSubscriberId);
        setReceiverSubscriberId(receiverSubscriberId);
        setStartTimestamp(startTimestamp);
        setEndTimestamp(endTimestamp);
        resetChangedOnNotNull();
    }
}
