/*
 * This file is generated by jOOQ.
 */
package ru.crackedglass.nexign_demo.entities.jooq;


import ru.crackedglass.nexign_demo.entities.jooq.tables.Cdrs;
import ru.crackedglass.nexign_demo.entities.jooq.tables.Subscribers;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>CDRS</code>.
     */
    public static final Cdrs CDRS = Cdrs.CDRS;

    /**
     * The table <code>SUBSCRIBERS</code>.
     */
    public static final Subscribers SUBSCRIBERS = Subscribers.SUBSCRIBERS;
}
