/*
 * This file is generated by jOOQ.
 */
package ru.crackedglass.nexign_demo.entities.jooq;


import ru.crackedglass.nexign_demo.entities.jooq.tables.Cdr;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>CDR</code>.
     */
    public static final Cdr CDR = Cdr.CDR;
}
